name: OnPushTag

#動作するトリガー（前提条件）
#masterブランチにタグ付きでpushされた場合のみ発動
on:
  push:
#    branches: [ master ]
    tags: 
      - 'v*'

#ワークフローの実行
#参考：https://proudust.github.io/20191220-create-release-with-ghactions/
jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      #セットアップ
      - uses: actions/checkout@v1



      # env.RELEASE_VERSIONにバージョン名（タグ名）を代入
      - name: Set env RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      # env.REPOSITORY_NAMEにリポジトリ名を代入
      - name: Set env REPOSITORY_NAME
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*\/}" >> $GITHUB_ENV


      # ビルド処理(Githubからダウンロード)
      - name: Source Download
        run: |
          wget https://github.com/average34/${{ env.REPOSITORY_NAME }}/archive/${{ env.RELEASE_VERSION }}.zip -O ${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_VERSION }}.zip



      #Github上でリリースを作成
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # リリースのタグ (必須)
          tag_name: ${{ github.ref }}
          # リリースのタイトル (必須)
          # リポジトリ名とタグ名を出力するように。
          release_name: 東方旧作風効果音素材 ${{ github.ref }}
          # リリースのタイトル (省略可能)
          body: |
            東方旧作風効果音素材  
            ## ダウンロード  
            下の「Assets」タブを開き、[「${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_VERSION }}.zip」をダウンロード](https://github.com/average34/${{ env.REPOSITORY_NAME }}/releases/download/${{ env.RELEASE_VERSION }}/${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_VERSION }}.zip)してください。

            ## 使い方
            「東方旧作再現効果音wav」フォルダの中に
            効果音のwavが入っています。
            直下のフォルダにはMMLファイル(.mml)とPMDファイル(.M)が入っており、
            それぞれテキストエディタと[FMPMD](http://c60.la.coocan.jp/fmpmd.html)で開くことができます。

            ## ライセンス
            以下の署名さえあればどなたでもご自由に商用利用可能です。
            ただし、これは上海アリス幻樂団公式の作品ではないため、まるで公式の素材であるかのような虚偽の記載はしないでください。
            (C) Copyright 2022 ここから先、34小節目。  
            [CC BY 4.0  ![CC BY 4.0](LICENCE_CC_BY_4.0.png)](https://creativecommons.org/licenses/by/4.0/deed.ja)
          # 下書き状態で作成する場合は true (省略時 false)
          draft: true
          # プレリリース表示を付ける場合は true (省略時 false)
          prerelease: false
      
      # リリースしたものにzipファイルを追加
      - uses: actions/upload-release-asset@master
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_VERSION }}.zip
          asset_name: ${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip

